// Generated from integrations/linear/mcp-catalog.ts + mcp-snapshot.json (npm run mcp:import -- generate linear).
// Curate the catalog and regenerate rather than hand-editing this file.
import type { ActionMeta } from "@/contracts/actionMeta";

/** Builder-facing metadata for `linear:create_issue`. */
export const createIssueMeta: ActionMeta = {
  key: "linear:create_issue",
  provider: "linear",
  type: "create_issue",
  displayName: "Create Issue",
  description: "Create a new issue in a Linear team, with optional description, assignee, state, labels, project, priority, and due date.",
  category: "developer",
  requiresIntegration: true,
  fields: [
    {
      name: "title",
      label: "Title",
      description: "Issue title (required when creating)",
      type: "text",
      required: true,
    },
    {
      name: "description",
      label: "Description",
      description: "Content as Markdown. Do not escape the string — use literal newlines and special characters, not escape sequences. To mention a user, use @displayName (e.g., @johndoe)",
      type: "textarea",
      required: false,
    },
    {
      name: "team",
      label: "Team",
      description: "Team the issue belongs to — pick one, or type a team name/ID.",
      type: "combobox",
      required: true,
      optionsSource: "linear:teams",
      allowManualEntry: true,
    },
    {
      name: "cycle",
      label: "Cycle",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "milestone",
      label: "Milestone",
      description: "Milestone name or ID",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "priority",
      label: "Priority",
      description: "Priority level for the new issue.",
      type: "select",
      required: false,
      options: [
        {
          value: "0",
          label: "No priority",
        },
        {
          value: "1",
          label: "Urgent",
        },
        {
          value: "2",
          label: "High",
        },
        {
          value: "3",
          label: "Medium",
        },
        {
          value: "4",
          label: "Low",
        },
      ],
    },
    {
      name: "project",
      label: "Project",
      description: "Project to add the issue to — pick from the list or type a project name/ID.",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:projects",
      allowManualEntry: true,
    },
    {
      name: "state",
      label: "State",
      description: "Workflow state — pick a team first, then choose a state (or type a state name/ID).",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:issue_statuses",
      allowManualEntry: true,
    },
    {
      name: "assignee",
      label: "Assignee",
      description: "Assignee — pick a user, or type a name, email, or \"me\".",
      type: "combobox",
      required: false,
      optionsSource: "linear:assignees",
      allowManualEntry: true,
    },
    {
      name: "delegate",
      label: "Delegate",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "labels",
      label: "Labels",
      description: "Labels to apply — pick from the list or type label names/IDs.",
      type: "string-array",
      required: false,
      optionsSource: "linear:labels",
      allowManualEntry: true,
    },
    {
      name: "dueDate",
      label: "Due date",
      description: "Due date (YYYY-MM-DD).",
      type: "date",
      required: false,
    },
    {
      name: "slaBreachesAt",
      label: "SLA breach time",
      type: "datetime-utc",
      required: false,
      advanced: true,
    },
    {
      name: "slaType",
      label: "SLA day counting",
      description: "SLA day counting type: \"all\" or \"onlyBusinessDays\". Only use with slaBreachesAt",
      type: "select",
      required: false,
      options: [
        {
          value: "all",
          label: "All",
        },
        {
          value: "onlyBusinessDays",
          label: "Only business days",
        },
      ],
      advanced: true,
    },
    {
      name: "parentId",
      label: "Parent issue",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "estimate",
      label: "Estimate",
      type: "number",
      required: false,
      numeric: {
        min: 0,
      },
      advanced: true,
    },
    {
      name: "links",
      label: "Links",
      description: "Link attachments to add [{url, title}]. Append-only; existing links are never removed",
      type: "object-list",
      required: false,
      itemFields: [
        {
          name: "url",
          label: "Url",
          type: "text",
          required: true,
        },
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
      ],
      advanced: true,
    },
    {
      name: "setReleases",
      label: "Set releases",
      description: "Replace all releases on the issue with these. Cannot be combined with addReleases/removeReleases",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "addReleases",
      label: "Add releases",
      description: "Release IDs or slugs to add. Append-only; existing releases are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blocks",
      label: "Blocks",
      description: "Issue IDs/identifiers this blocks. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blockedBy",
      label: "Blocked by",
      description: "Issue IDs/identifiers blocking this. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "relatedTo",
      label: "Related to",
      description: "Related issue IDs/identifiers. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
  ],
  outputs: [
    {
      name: "id",
      type: "string",
      description: "The new issue's unique ID.",
    },
    {
      name: "title",
      type: "string",
      description: "The issue title.",
    },
    {
      name: "url",
      type: "string",
      description: "Direct link to the issue in Linear (contains its LIN-… reference — use this for Slack/downstream).",
    },
    {
      name: "status",
      type: "string",
      description: "Current workflow state name (e.g. Backlog, In Progress).",
    },
    {
      name: "team",
      type: "string",
      description: "Name of the team the issue belongs to.",
    },
    {
      name: "project",
      type: "string",
      description: "Name of the project the issue is in (empty when none).",
    },
    {
      name: "createdAt",
      type: "string",
      description: "When the issue was created (ISO-8601 UTC).",
    },
  ],
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: 20,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "medium",
};
