// Generated from integrations/linear/mcp-catalog.ts + mcp-snapshot.json (npm run mcp:import -- generate linear).
// Curate the catalog and regenerate rather than hand-editing this file.
import type { ActionMeta } from "@/contracts/actionMeta";

/** Builder-facing metadata for `linear:create_issue`. */
export const createIssueMeta: ActionMeta = {
  key: "linear:create_issue",
  provider: "linear",
  type: "create_issue",
  displayName: "Create Issue",
  description: "Create a new issue in a Linear team, with optional description, assignee, state, labels, project, priority, and due date.",
  category: "developer",
  requiresIntegration: true,
  fields: [
    {
      name: "title",
      label: "Title",
      description: "Issue title (required when creating)",
      type: "text",
      required: true,
    },
    {
      name: "description",
      label: "Description",
      description: "Content as Markdown. Do not escape the string — use literal newlines and special characters, not escape sequences. To mention a user, use @displayName (e.g., @johndoe)",
      type: "textarea",
      required: false,
    },
    {
      name: "team",
      label: "Team",
      description: "Team name or ID (required when creating)",
      type: "text",
      required: true,
    },
    {
      name: "cycle",
      label: "Cycle",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "milestone",
      label: "Milestone",
      description: "Milestone name or ID",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "priority",
      label: "Priority",
      description: "0=None, 1=Urgent, 2=High, 3=Medium, 4=Low",
      type: "number",
      required: false,
    },
    {
      name: "project",
      label: "Project",
      description: "Project name, ID, or slug",
      type: "text",
      required: false,
    },
    {
      name: "state",
      label: "State",
      description: "State type, name, or ID",
      type: "text",
      required: false,
    },
    {
      name: "assignee",
      label: "Assignee",
      type: "text",
      required: false,
    },
    {
      name: "delegate",
      label: "Delegate",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "labels",
      label: "Labels",
      description: "Label names or IDs",
      type: "string-array",
      required: false,
    },
    {
      name: "dueDate",
      label: "Due date",
      description: "Due date (ISO format)",
      type: "text",
      required: false,
    },
    {
      name: "parentId",
      label: "Parent id",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "estimate",
      label: "Estimate",
      description: "Issue estimate value",
      type: "number",
      required: false,
      advanced: true,
    },
    {
      name: "links",
      label: "Links",
      description: "Link attachments to add [{url, title}]. Append-only; existing links are never removed",
      type: "object-list",
      required: false,
      itemFields: [
        {
          name: "url",
          label: "Url",
          type: "text",
          required: true,
        },
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
      ],
      advanced: true,
    },
    {
      name: "blocks",
      label: "Blocks",
      description: "Issue IDs/identifiers this blocks. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blockedBy",
      label: "Blocked by",
      description: "Issue IDs/identifiers blocking this. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "relatedTo",
      label: "Related to",
      description: "Related issue IDs/identifiers. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
  ],
  outputs: [
    {
      name: "text",
      type: "string",
      description: "Text returned by the provider for this call.",
    },
  ],
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: 20,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "medium",
};
