// Generated from integrations/linear/mcp-catalog.ts + mcp-snapshot.json (npm run mcp:import -- generate linear).
// Curate the catalog and regenerate rather than hand-editing this file.
import type { ActionMeta } from "@/contracts/actionMeta";

/** Builder-facing metadata for `linear:find_issues`. */
export const findIssuesMeta: ActionMeta = {
  key: "linear:find_issues",
  provider: "linear",
  type: "find_issues",
  displayName: "Find Issues",
  description: "Search and filter issues in the Linear workspace by text, team, state, assignee, label, project, cycle, or priority. Returns one page of results.",
  category: "developer",
  requiresIntegration: true,
  fields: [
    {
      name: "limit",
      label: "Limit",
      description: "Max results (default 50, max 250)",
      type: "number",
      required: false,
      defaultValue: 50,
      numeric: {
        min: 1,
        max: 250,
      },
      advanced: true,
    },
    {
      name: "cursor",
      label: "Cursor",
      description: "Next-page cursor from a previous Find Issues step.",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "orderBy",
      label: "Order by",
      description: "Sort: createdAt | updatedAt",
      type: "select",
      required: false,
      defaultValue: "updatedAt",
      options: [
        {
          value: "createdAt",
          label: "Created at",
        },
        {
          value: "updatedAt",
          label: "Updated at",
        },
      ],
      advanced: true,
    },
    {
      name: "query",
      label: "Query",
      description: "Search issue title or description",
      type: "text",
      required: false,
    },
    {
      name: "team",
      label: "Team",
      description: "Team name or ID",
      type: "combobox",
      required: false,
      optionsSource: "linear:teams",
    },
    {
      name: "state",
      label: "State",
      description: "State type, name, or ID",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:issue_statuses",
    },
    {
      name: "cycle",
      label: "Cycle",
      description: "Cycle name, number, or ID",
      type: "text",
      required: false,
    },
    {
      name: "label",
      label: "Label",
      description: "Label name or ID",
      type: "combobox",
      required: false,
      optionsSource: "linear:labels",
    },
    {
      name: "assignee",
      label: "Assignee",
      type: "combobox",
      required: false,
      optionsSource: "linear:assignees",
    },
    {
      name: "delegate",
      label: "Delegate",
      description: "Agent name or ID. When the user asks to delegate to \"Linear\" or \"the Linear agent\", this refers to the \"Linear\" app user specifically",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "project",
      label: "Project",
      description: "Project name, ID, or slug",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:projects",
    },
    {
      name: "release",
      label: "Release",
      description: "Release ID or slug",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "priority",
      label: "Priority",
      description: "Only return issues at this priority level.",
      type: "select",
      required: false,
      options: [
        {
          value: "0",
          label: "No priority",
        },
        {
          value: "1",
          label: "Urgent",
        },
        {
          value: "2",
          label: "High",
        },
        {
          value: "3",
          label: "Medium",
        },
        {
          value: "4",
          label: "Low",
        },
      ],
    },
    {
      name: "parentId",
      label: "Parent issue",
      description: "Parent issue ID or identifier (e.g., LIN-123)",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "createdAt",
      label: "Created at",
      description: "Created after: ISO-8601 date/duration (e.g., -P1D)",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "updatedAt",
      label: "Updated at",
      description: "Updated after: ISO-8601 date/duration (e.g., -P1D)",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "includeArchived",
      label: "Include archived",
      description: "Include archived items",
      type: "boolean",
      required: false,
      defaultValue: true,
      advanced: true,
    },
  ],
  outputs: [
    {
      name: "issues",
      type: "array",
      description: "One page of matching issues (each: id, title, description, url, status, statusType, team, teamId, priority, createdAt, updatedAt, labels).",
    },
    {
      name: "hasNextPage",
      type: "boolean",
      description: "True when more issues exist beyond this page.",
    },
    {
      name: "cursor",
      type: "string",
      description: "Opaque next-page token — pass to a later Find Issues run's Cursor to page forward.",
    },
  ],
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: 10,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "low",
};
