// Generated from integrations/linear/mcp-catalog.ts + mcp-snapshot.json (npm run mcp:import -- generate linear).
// Curate the catalog and regenerate rather than hand-editing this file.
import type { ActionMeta } from "@/contracts/actionMeta";

/** Builder-facing metadata for `linear:update_issue`. */
export const updateIssueMeta: ActionMeta = {
  key: "linear:update_issue",
  provider: "linear",
  type: "update_issue",
  displayName: "Update Issue",
  description: "Update an existing Linear issue by ID or identifier (e.g. LIN-123) — state, assignee, priority, labels, project, due date, relations.",
  category: "developer",
  requiresIntegration: true,
  fields: [
    {
      name: "id",
      label: "Issue",
      description: "Issue ID or identifier (e.g. LIN-123).",
      type: "text",
      required: true,
    },
    {
      name: "title",
      label: "Title",
      description: "Issue title (required when creating)",
      type: "text",
      required: false,
    },
    {
      name: "description",
      label: "Description",
      description: "Content as Markdown. Do not escape the string — use literal newlines and special characters, not escape sequences. To mention a user, use @displayName (e.g., @johndoe)",
      type: "textarea",
      required: false,
    },
    {
      name: "team",
      label: "Team",
      description: "Team name or ID (required when creating)",
      type: "text",
      required: false,
    },
    {
      name: "cycle",
      label: "Cycle",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "milestone",
      label: "Milestone",
      description: "Milestone name or ID",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "priority",
      label: "Priority",
      description: "0=None, 1=Urgent, 2=High, 3=Medium, 4=Low",
      type: "number",
      required: false,
    },
    {
      name: "project",
      label: "Project",
      type: "text",
      required: false,
    },
    {
      name: "state",
      label: "State",
      description: "State type, name, or ID",
      type: "text",
      required: false,
    },
    {
      name: "assignee",
      label: "Assignee",
      type: "text",
      required: false,
    },
    {
      name: "delegate",
      label: "Delegate",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "labels",
      label: "Labels",
      description: "Label names or IDs as a JSON array of strings (e.g. [\"Bug\", \"Urgent\"]). Replaces the full label set; existing labels not included are removed. Omit to leave labels unchanged",
      type: "string-array",
      required: false,
    },
    {
      name: "dueDate",
      label: "Due date",
      type: "text",
      required: false,
    },
    {
      name: "slaBreachesAt",
      label: "Sla breaches at",
      type: "datetime-utc",
      required: false,
      advanced: true,
    },
    {
      name: "slaType",
      label: "Sla type",
      description: "SLA day counting type: \"all\" or \"onlyBusinessDays\". Only use with slaBreachesAt",
      type: "select",
      required: false,
      options: [
        {
          value: "all",
          label: "All",
        },
        {
          value: "onlyBusinessDays",
          label: "Only business days",
        },
      ],
      advanced: true,
    },
    {
      name: "parentId",
      label: "Parent id",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "estimate",
      label: "Estimate",
      type: "number",
      required: false,
      advanced: true,
    },
    {
      name: "links",
      label: "Links",
      description: "Link attachments to add [{url, title}]. Append-only; existing links are never removed",
      type: "object-list",
      required: false,
      itemFields: [
        {
          name: "url",
          label: "Url",
          type: "text",
          required: true,
        },
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
      ],
      advanced: true,
    },
    {
      name: "setReleases",
      label: "Set releases",
      description: "Replace all releases on the issue with these. Cannot be combined with addReleases/removeReleases",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "addReleases",
      label: "Add releases",
      description: "Release IDs or slugs to add. Append-only; existing releases are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeReleases",
      label: "Remove releases",
      description: "Release IDs or slugs to remove. Only valid when updating an existing issue",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blocks",
      label: "Blocks",
      description: "Issue IDs/identifiers this blocks. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blockedBy",
      label: "Blocked by",
      description: "Issue IDs/identifiers blocking this. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "relatedTo",
      label: "Related to",
      description: "Related issue IDs/identifiers. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "duplicateOf",
      label: "Duplicate of",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "removeBlocks",
      label: "Remove blocks",
      description: "Issue IDs/identifiers to stop blocking",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeBlockedBy",
      label: "Remove blocked by",
      description: "Issue IDs/identifiers to remove as blockers of this issue",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeRelatedTo",
      label: "Remove related to",
      description: "Related issue IDs/identifiers to remove",
      type: "string-array",
      required: false,
      advanced: true,
    },
  ],
  outputs: [
    {
      name: "text",
      type: "string",
      description: "Text returned by the provider for this call.",
    },
  ],
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: 30,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "medium",
};
