// Generated from integrations/linear/mcp-catalog.ts + mcp-snapshot.json (npm run mcp:import -- generate linear).
// Curate the catalog and regenerate rather than hand-editing this file.
import type { ActionMeta } from "@/contracts/actionMeta";

/** Builder-facing metadata for `linear:update_issue`. */
export const updateIssueMeta: ActionMeta = {
  key: "linear:update_issue",
  provider: "linear",
  type: "update_issue",
  displayName: "Update Issue",
  description: "Update an existing Linear issue by ID or identifier (e.g. LIN-123) — state, assignee, priority, labels, project, due date, relations.",
  category: "developer",
  requiresIntegration: true,
  fields: [
    {
      name: "id",
      label: "Issue",
      description: "Issue ID or identifier (e.g. LIN-123).",
      type: "text",
      required: true,
    },
    {
      name: "title",
      label: "Title",
      description: "Issue title (required when creating)",
      type: "text",
      required: false,
    },
    {
      name: "description",
      label: "Description",
      description: "Content as Markdown. Do not escape the string — use literal newlines and special characters, not escape sequences. To mention a user, use @displayName (e.g., @johndoe)",
      type: "textarea",
      required: false,
    },
    {
      name: "team",
      label: "Team",
      description: "Move the issue to a different team — pick one, or type a team name/ID (optional).",
      type: "combobox",
      required: false,
      optionsSource: "linear:teams",
      allowManualEntry: true,
    },
    {
      name: "cycle",
      label: "Cycle",
      description: "Cycle name, number, or ID.",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "milestone",
      label: "Milestone",
      description: "Milestone name or ID",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "priority",
      label: "Priority",
      description: "Change the issue's priority level.",
      type: "select",
      required: false,
      options: [
        {
          value: "0",
          label: "No priority",
        },
        {
          value: "1",
          label: "Urgent",
        },
        {
          value: "2",
          label: "High",
        },
        {
          value: "3",
          label: "Medium",
        },
        {
          value: "4",
          label: "Low",
        },
      ],
    },
    {
      name: "project",
      label: "Project",
      description: "Move the issue to a project — pick from the list or type a project name/ID.",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:projects",
      allowManualEntry: true,
    },
    {
      name: "state",
      label: "State",
      description: "Move the issue to a workflow state — pick a team first, then a state (or type a state name/ID).",
      type: "combobox",
      required: false,
      dependsOn: [
        "team",
      ],
      optionsSource: "linear:issue_statuses",
      allowManualEntry: true,
    },
    {
      name: "assignee",
      label: "Assignee",
      description: "Reassign the issue — pick a user, or type a name, email, or \"me\".",
      type: "combobox",
      required: false,
      optionsSource: "linear:assignees",
      allowManualEntry: true,
    },
    {
      name: "delegate",
      label: "Delegate",
      description: "Agent name or ID.",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "labels",
      label: "Labels",
      description: "Replace the issue's labels — pick from the list or type label names/IDs. Leave empty to keep existing labels.",
      type: "string-array",
      required: false,
      optionsSource: "linear:labels",
      allowManualEntry: true,
    },
    {
      name: "dueDate",
      label: "Due date",
      description: "Due date (YYYY-MM-DD).",
      type: "date",
      required: false,
    },
    {
      name: "slaBreachesAt",
      label: "SLA breach time",
      description: "ISO-8601 timestamp when the SLA will breach.",
      type: "datetime-utc",
      required: false,
      advanced: true,
    },
    {
      name: "slaType",
      label: "SLA day counting",
      description: "SLA day counting type: \"all\" or \"onlyBusinessDays\". Only use with slaBreachesAt",
      type: "select",
      required: false,
      options: [
        {
          value: "all",
          label: "All",
        },
        {
          value: "onlyBusinessDays",
          label: "Only business days",
        },
      ],
      advanced: true,
    },
    {
      name: "parentId",
      label: "Parent issue",
      description: "Parent issue ID or identifier (e.g., LIN-123).",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "estimate",
      label: "Estimate",
      description: "Issue estimate value. Omit to leave it unchanged.",
      type: "number",
      required: false,
      numeric: {
        min: 0,
      },
      advanced: true,
    },
    {
      name: "links",
      label: "Links",
      description: "Link attachments to add [{url, title}]. Append-only; existing links are never removed",
      type: "object-list",
      required: false,
      itemFields: [
        {
          name: "url",
          label: "Url",
          type: "text",
          required: true,
        },
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
      ],
      advanced: true,
    },
    {
      name: "setReleases",
      label: "Set releases",
      description: "Replace all releases on the issue with these. Cannot be combined with addReleases/removeReleases",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "addReleases",
      label: "Add releases",
      description: "Release IDs or slugs to add. Append-only; existing releases are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeReleases",
      label: "Remove releases",
      description: "Release IDs or slugs to remove. Only valid when updating an existing issue",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blocks",
      label: "Blocks",
      description: "Issue IDs/identifiers this blocks. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "blockedBy",
      label: "Blocked by",
      description: "Issue IDs/identifiers blocking this. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "relatedTo",
      label: "Related to",
      description: "Related issue IDs/identifiers. Append-only; existing relations are never removed",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "duplicateOf",
      label: "Duplicate of",
      description: "Duplicate of issue ID/identifier.",
      type: "text",
      required: false,
      advanced: true,
    },
    {
      name: "removeBlocks",
      label: "Remove blocks",
      description: "Issue IDs/identifiers to stop blocking",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeBlockedBy",
      label: "Remove blocked by",
      description: "Issue IDs/identifiers to remove as blockers of this issue",
      type: "string-array",
      required: false,
      advanced: true,
    },
    {
      name: "removeRelatedTo",
      label: "Remove related to",
      description: "Related issue IDs/identifiers to remove",
      type: "string-array",
      required: false,
      advanced: true,
    },
  ],
  outputs: [
    {
      name: "id",
      type: "string",
      description: "The issue's unique ID.",
    },
    {
      name: "title",
      type: "string",
      description: "The issue title after the update.",
    },
    {
      name: "url",
      type: "string",
      description: "Direct link to the issue in Linear (contains its LIN-… reference).",
    },
    {
      name: "status",
      type: "string",
      description: "Current workflow state name after the update.",
    },
    {
      name: "updatedAt",
      type: "string",
      description: "When the issue was last updated (ISO-8601 UTC).",
    },
  ],
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: 30,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "medium",
};
