import { NextRequest, NextResponse } from 'next/server'
import { google } from 'googleapis'
import { getDecryptedAccessToken } from '@/lib/workflows/actions/core/getDecryptedAccessToken'
import { logger } from '@/lib/utils/logger'

/**
 * POST /api/google-meet
 * Creates a temporary Google Calendar event with Google Meet conference
 * Returns the actual Meet link generated by Google
 */
export async function POST(request: NextRequest) {
  try {
    const { userId, settings } = await request.json()

    if (!userId) {
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      )
    }

    // Get the decrypted access token for Google Calendar
    const accessToken = await getDecryptedAccessToken(userId, 'google-calendar')

    // Create OAuth2 client
    const oauth2Client = new google.auth.OAuth2()
    oauth2Client.setCredentials({ access_token: accessToken })

    // Create calendar API client
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client })

    // Create a temporary event with Google Meet
    // This event will be deleted when the workflow executes or when user clicks X
    const now = new Date()
    const endTime = new Date(now.getTime() + 60 * 60 * 1000) // 1 hour later

    const eventData: any = {
      summary: '[ChainReact] Google Meet Placeholder',
      description: 'Temporary event created to generate Google Meet link. This will be replaced when the workflow executes.',
      start: {
        dateTime: now.toISOString(),
        timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
      },
      end: {
        dateTime: endTime.toISOString(),
        timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
      },
      conferenceData: {
        createRequest: {
          requestId: `chainreact_${Date.now()}`,
          conferenceSolutionKey: { type: 'hangoutsMeet' }
        }
      },
      // Make it private and transparent so it doesn't clutter the calendar
      visibility: 'private',
      transparency: 'transparent'
    }

    // Create the event with conference data
    const response = await calendar.events.insert({
      calendarId: 'primary',
      requestBody: eventData,
      conferenceDataVersion: 1
    })

    const createdEvent = response.data

    // Extract the Meet link
    const meetLink = createdEvent.conferenceData?.entryPoints?.find(
      (entry) => entry.entryPointType === 'video'
    )?.uri || createdEvent.hangoutLink

    if (!meetLink) {
      // If Meet link creation failed, delete the event and return error
      if (createdEvent.id) {
        await calendar.events.delete({
          calendarId: 'primary',
          eventId: createdEvent.id
        })
      }
      return NextResponse.json(
        { error: 'Failed to create Google Meet link' },
        { status: 500 }
      )
    }

    // Extract the Meet ID from the link
    const meetId = meetLink.split('/').pop() || ''

    logger.info('✅ [Google Meet] Created temporary event with Meet link', {
      eventId: createdEvent.id,
      meetLink
    })

    return NextResponse.json({
      success: true,
      data: {
        link: meetLink,
        id: meetId,
        eventId: createdEvent.id,
        settings: settings || {
          accessType: 'open',
          allowJoinBeforeHost: true,
          muteOnEntry: false,
          enableRecording: false
        }
      }
    })
  } catch (error: any) {
    logger.error('❌ [Google Meet] Error creating Meet link:', error)

    // Check if it's a token error
    if (error.message?.includes('401') || error.message?.includes('Unauthorized') || error.code === 401) {
      return NextResponse.json(
        { error: 'Google Calendar authentication failed. Please reconnect your account.' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: error.message || 'Failed to create Google Meet link' },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/google-meet
 * Deletes the temporary Google Calendar event created for the Meet link
 */
export async function DELETE(request: NextRequest) {
  try {
    const { userId, eventId } = await request.json()

    if (!userId || !eventId) {
      return NextResponse.json(
        { error: 'User ID and event ID are required' },
        { status: 400 }
      )
    }

    // Get the decrypted access token for Google Calendar
    const accessToken = await getDecryptedAccessToken(userId, 'google-calendar')

    // Create OAuth2 client
    const oauth2Client = new google.auth.OAuth2()
    oauth2Client.setCredentials({ access_token: accessToken })

    // Create calendar API client
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client })

    // Delete the temporary event
    await calendar.events.delete({
      calendarId: 'primary',
      eventId: eventId
    })

    logger.info('✅ [Google Meet] Deleted temporary event', { eventId })

    return NextResponse.json({
      success: true,
      message: 'Google Meet link deleted'
    })
  } catch (error: any) {
    logger.error('❌ [Google Meet] Error deleting event:', error)

    // If event not found, consider it successful (already deleted)
    if (error.code === 404 || error.message?.includes('404')) {
      return NextResponse.json({
        success: true,
        message: 'Event already deleted or not found'
      })
    }

    // Check if it's a token error
    if (error.message?.includes('401') || error.message?.includes('Unauthorized') || error.code === 401) {
      return NextResponse.json(
        { error: 'Google Calendar authentication failed. Please reconnect your account.' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: error.message || 'Failed to delete Google Meet link' },
      { status: 500 }
    )
  }
}
