/**
 * Internal MCP server — pure helpers for the Phase 2D report tools
 * (`generate_diagnostic_report` / `generate_deploy_readiness_report`).
 *
 * Pure / local — no app import, no I/O, no network. Every value rendered here
 * comes from an already-sanitized doctor `DoctorResult` (the gated route
 * sanitizes) or from the already-redacted output of an existing safe check tool.
 * These helpers ADD NO new diagnostic brain and ACCESS NO data — they only
 * format and classify what the composed tools already produced.
 */
import type { DoctorResult, Section, SectionStatus } from "./doctorShared";

/** Shared, copy-pasteable safety footer for the diagnostic report. */
export const DIAGNOSTIC_SAFETY_NOTE =
  "Sanitized internal diagnostic report — composed from existing gated diagnostics/doctors. " +
  "It contains status enums, counts, node ids, and field NAMES only. No secrets, tokens, env " +
  "values, credentials, raw provider payloads, raw config values, raw DB errors, stack traces, " +
  "or private user/customer data are included. Internal developer output only.";

export type DiagnosticReportType = "workflow" | "provider" | "accountIntegration";

export interface DiagnosticReportOptions {
  /** When set, only these section names are rendered (others dropped). */
  readonly includeSections?: readonly string[];
  /** Include the "Unavailable / deferred checks" block (default true). */
  readonly includeUnavailable?: boolean;
  /** Cap on findings shown per section (default 12). */
  readonly maxFindings?: number;
}

const DEFAULT_MAX_FINDINGS = 12;

/** Structured, leak-safe metadata returned alongside the Markdown body. */
export interface DiagnosticReportSummary {
  readonly reportType: DiagnosticReportType;
  readonly title: string;
  readonly overallStatus: string;
  readonly generatedByTool: "generate_diagnostic_report";
  readonly sourceTools: readonly string[];
  readonly sections: ReadonlyArray<{ name: string; status: SectionStatus; summary: string; findingCount: number }>;
  readonly nextSteps: readonly string[];
  readonly unavailableSections: ReadonlyArray<{ section: string; reason: string }>;
  readonly safetyNote: string;
}

function filterSections(
  sections: readonly Section[],
  include?: readonly string[],
): readonly Section[] {
  if (!include || include.length === 0) return sections;
  const wanted = new Set(include);
  return sections.filter((s) => wanted.has(s.name));
}

/** Build the structured (leak-safe) summary object for a diagnostic report. */
export function buildDiagnosticSummary(
  reportType: DiagnosticReportType,
  title: string,
  result: DoctorResult,
  options: DiagnosticReportOptions = {},
): DiagnosticReportSummary {
  const sections = filterSections(result.sections, options.includeSections);
  return {
    reportType,
    title,
    overallStatus: result.overall,
    generatedByTool: "generate_diagnostic_report",
    sourceTools: result.sourceTools,
    sections: sections.map((s) => ({
      name: s.name,
      status: s.status,
      summary: s.summary,
      findingCount: s.findings?.length ?? 0,
    })),
    nextSteps: result.nextSteps,
    unavailableSections: options.includeUnavailable === false ? [] : result.unavailable,
    safetyNote: DIAGNOSTIC_SAFETY_NOTE,
  };
}

function sectionBlock(s: Section, maxFindings: number): string[] {
  const lines = [`### ${s.name} — ${s.status.toUpperCase()}`, s.summary];
  const findings = (s.findings ?? []).slice(0, maxFindings);
  for (const f of findings) lines.push(`- ${f}`);
  const dropped = (s.findings?.length ?? 0) - findings.length;
  if (dropped > 0) lines.push(`- …and ${dropped} more finding(s) (capped at ${maxFindings}).`);
  return lines;
}

/**
 * Render a full diagnostic report: Markdown body + a fenced structured-metadata
 * block. Pure over an already-sanitized `DoctorResult`.
 */
export function renderDiagnosticReport(
  reportType: DiagnosticReportType,
  title: string,
  result: DoctorResult,
  options: DiagnosticReportOptions = {},
): string {
  const maxFindings = Math.max(1, options.maxFindings ?? DEFAULT_MAX_FINDINGS);
  const sections = filterSections(result.sections, options.includeSections);
  const summary = buildDiagnosticSummary(reportType, title, result, options);

  const out: string[] = [];
  out.push(`# Diagnostic Report — ${title}`);
  out.push("");
  out.push(`**Report type:** ${reportType}`);
  out.push(`**Overall status:** ${result.overall}`);
  out.push(`**Generated by:** generate_diagnostic_report`);
  out.push("");

  // Summary
  out.push("## Summary");
  if (sections.length === 0) {
    out.push("No sections were available to report.");
  } else {
    for (const s of sections) out.push(`- **${s.name}**: ${s.status.toUpperCase()} — ${s.summary}`);
  }
  out.push("");

  // Sections (detail)
  out.push("## Sections");
  if (sections.length === 0) {
    out.push("_(none)_");
  } else {
    for (const s of sections) out.push(...sectionBlock(s, maxFindings));
  }
  out.push("");

  // Findings by severity (grouped from section status — no string parsing)
  out.push("## Findings by severity");
  const errorSecs = sections.filter((s) => s.status === "blocked");
  const warnSecs = sections.filter((s) => s.status === "warning");
  out.push("### Errors");
  if (errorSecs.length === 0) out.push("- _(none)_");
  else for (const s of errorSecs) out.push(`- **${s.name}**: ${s.summary}`);
  out.push("### Warnings");
  if (warnSecs.length === 0) out.push("- _(none)_");
  else for (const s of warnSecs) out.push(`- **${s.name}**: ${s.summary}`);
  out.push("");

  // Prioritized next steps
  out.push("## Prioritized next steps");
  if (result.nextSteps.length === 0) out.push("_(none — nothing actionable detected)_");
  else result.nextSteps.forEach((n, i) => out.push(`${i + 1}. ${n}`));
  out.push("");

  // Sources used
  out.push("## Sources used");
  if (result.sourceTools.length === 0) out.push("- _(none)_");
  else for (const t of result.sourceTools) out.push(`- ${t}`);
  out.push("");

  // Unavailable / deferred
  if (options.includeUnavailable !== false) {
    out.push("## Unavailable / deferred checks");
    if (result.unavailable.length === 0) out.push("- _(none)_");
    else for (const u of result.unavailable) out.push(`- **${u.section}**: ${u.reason}`);
    out.push("");
  }

  // Safety note
  out.push("## Safety note");
  out.push(DIAGNOSTIC_SAFETY_NOTE);
  out.push("");

  // Structured metadata appendix
  out.push("## Structured metadata");
  out.push("```json");
  out.push(JSON.stringify(summary, null, 2));
  out.push("```");

  return out.join("\n");
}

// ──────────────────────── deploy-readiness helpers ────────────────────────

export type CheckStatus = "passed" | "failed" | "warning" | "info";
export type ReadinessStatus = "ready" | "blocked" | "review_needed" | "unknown";

export interface CheckOutcome {
  readonly name: string;
  readonly status: CheckStatus;
  readonly headline: string;
}

/**
 * Classify the already-redacted output of a safe check tool into a coarse
 * status. Pure; recognizes the command-wrapper (`exit code: N`), jest-runner
 * (`result: PASSED/FAILED`), and smoke-summary output shapes.
 */
export function classifyCheckOutput(toolName: string, output: string): CheckOutcome {
  const firstLine = output.split("\n").find((l) => l.trim().length > 0)?.trim() ?? "(no output)";

  if (toolName === "summarize_last_test_failure") {
    if (/^No recent failure artifact|No failures in the latest artifact/.test(output)) {
      return { name: toolName, status: "info", headline: firstLine };
    }
    if (/Latest test failure/.test(output)) {
      return { name: toolName, status: "warning", headline: "recent test failure present in smoke artifact" };
    }
    return { name: toolName, status: "info", headline: firstLine };
  }

  // command-wrapper output: "exit code: N\n\n..."
  const exit = output.match(/^exit code:\s*(-?\d+)/m);
  if (exit) {
    const code = exit[1];
    return { name: toolName, status: code === "0" ? "passed" : "failed", headline: `exit code ${code}` };
  }

  // jest-runner output: "result: PASSED/FAILED/TIMEOUT/FAILED TO START"
  if (/result:\s*PASSED/.test(output)) return { name: toolName, status: "passed", headline: "PASSED" };
  const failed = output.match(/result:\s*(FAILED(?: TO START)?|TIMEOUT)/);
  if (failed) return { name: toolName, status: "failed", headline: failed[1] ?? "FAILED" };

  // command failed to start / timed out / validation error
  if (/timed out|failed to start|^Error:/m.test(output)) {
    return { name: toolName, status: "failed", headline: firstLine };
  }
  return { name: toolName, status: "warning", headline: "could not classify result" };
}

/** Aggregate the readiness verdict from the run checks + recommended count. */
export function deriveReadiness(
  mode: "advisory" | "runSafeChecks",
  checksRun: readonly CheckOutcome[],
  recommendedCount: number,
): ReadinessStatus {
  if (mode === "advisory") {
    return recommendedCount > 0 ? "review_needed" : "unknown";
  }
  if (checksRun.some((c) => c.status === "failed")) return "blocked";
  if (checksRun.length === 0) return "unknown";
  if (checksRun.some((c) => c.status === "warning")) return "review_needed";
  return "ready";
}

export const DEPLOY_NO_ACTION_STATEMENTS: readonly string[] = [
  "No push performed.",
  "No deploy performed.",
  "No database changes or migration application performed.",
];
