/**
 * Frozen minimal `.xlsx` workbook (base64) — smoke write-harness bootstrap asset.
 *
 * Excel has no `create_workbook` action, so an Excel WRITE smoke must bring its own
 * smoke-owned workbook: the harness uploads these bytes via the certified
 * `microsoft-onedrive:upload_file` (inline base64), then drives the Excel action
 * against the resulting drive-item id, and finally hard-removes the whole file via
 * `microsoft-onedrive:delete_item`. Never touches a user/customer workbook.
 *
 * This is a hand-built, dependency-free OOXML SpreadsheetML package (1898 bytes) with
 * exactly one worksheet `Sheet1` + a minimal styles part — the smallest body Microsoft
 * Graph's workbook API reliably OPENS (verified live: `worksheets` returns `["Sheet1"]`
 * and `worksheets/add` succeeds). It is FROZEN as a literal (not regenerated per run) so
 * it is reproducible regardless of the local zlib build. Contains no marker, no PII —
 * the smoke marker rides on the worksheet NAME the action under test creates, proven by
 * an independent `get_worksheets` read-back.
 */
export const MINIMAL_XLSX_BASE64 =
  "UEsDBBQAAAAIAAAAIQAKCHnMDAEAAKgCAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbK2SMU8DMQyFd35FlLW6pGVACPXaocAIDOUHmJyvFzVxotg9rv8e9VoYUKFLpzf4+X1PlufLIQbVY2GfqNYzM9UKyaXG06bW7+vn6l4rFqAGQiKs9R5ZLxc38/U+I6shBuJadyL5wVp2HUZgkzLSEEObSgRhk8rGZnBb2KC9nU7vrEskSFLJIUMv5o/Ywi6IehoE6VikYGCtVkfjgVVryDl4B+IT2Z6aX5TqRDAFw+jhzmeeDDFoe5ZwmPwNOO299liKb1C9QZEXiFhrOwT7mcr2I6Wt+T/kTMvUtt5hk9wuIonhXBAa7hAlBjOqieBpcpk/mtmOMrtykZ/8Cz1Y9gH52lcYQ7/Jdny0xRdQSwMEFAAAAAgAAAAhAAZZx4KzAAAAKAEAAAsAAABfcmVscy8ucmVsc43PsW7CMBDG8Z2nsG4nDgxVheKwICTWKn0A41wSK/ad5TOtefuuBTGwf/p9+nfHGoP6wSyeycCuaUEhOR49zQa+h/P2E5QUS6MNTGjgjgLHftN9YbDFM8nik6gaA4mBpZR00FrcgtFKwwmpxjBxjrZIw3nWybrVzqj3bfuh838D+gdTXUYD+TLuQA33hO/YPE3e4YndLSKVFxdPC1CDzTMWAzXoX87rlXltagyg+04/BPZ/UEsDBBQAAAAIAAAAIQB3QP7EvgAAABwBAAAPAAAAeGwvd29ya2Jvb2sueG1sjY/BTsMwEETvfIW198YJB4SiOL1USD0DH2DiTWPVuxvtuhD+HtHSO6cZjTRvNMN+o+I+US0LB+iaFhzyJCnzKcD728vuGZzVyCkWYQzwjQb78WH4Ej1/iJzdRoUtwFLr2ntv04IUrZEVeaMyi1Ks1oievK2KMdmCWKn4x7Z98hQzw43Q638YMs95woNMF0KuN4hiiTUL25JXg3G4LtifOo6EAV5/fQfumh1TgA6c9jkF0GPqwI+Dv9f8/dn4A1BLAwQUAAAACAAAACEA4EKWiskAAACoAQAAGgAAAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzrZC7asQwEEX7fIWYPpa9RQhh5W2WwLbB+QAhj22x0ozQTBL77wMJeSxskSLVcG9x7mH2hzUn84pVIpODrmnBIAUeI80OnofH23swop5Gn5jQwYYCh/5m/4TJa2SSJRYxa04kDhbV8mCthAWzl4YL0prTxDV7lYbrbIsPZz+j3bXtna2/GdBfMM1pdFBPYwdm2Ar+hc3TFAMeObxkJL0yYd+4nmVBVDCDrzOqg+9K7MfpmjUnsNdldv8pI7ollB+Tz/w1by8e3L8DUEsDBBQAAAAIAAAAIQCNlKlJ6gAAAJcBAAANAAAAeGwvc3R5bGVzLnhtbHWQvW7DMAyE9z6FwL2W3aEoCkkZAuQFkgJdFZtOBFCUIaqB3acv/AO0HjqRvPt4w5nDGEk9MEtIbKGpalDIbeoC3yx8XE7Pb6CkeO48JUYLEwoc3JORMhGe74hFjZFYLNxLGd61lvaO0UuVBuQxUp9y9EWqlG9ahoy+k/kpkn6p61cdfWBwpk9cRLXpi4uFZhOckW/18GShaUA7wz7ieh89hWsOs6hXchniTB+I9kGByJnBl4KZT4FIbftlGtACJ8Y1ZuGWIc5cU+4w74JWaUY305kWic5zD5/9Dh37Gfvrruy/2ELo30rdD1BLAwQUAAAACAAAACEAB5roooQAAACdAAAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbD3MMQ7CMAxA0Z1TRN6pCwNCKEkXxAngAFZr2orYqeIIyu2ROrB+6X3frZLcm4vNWQMcmhYca5+HWccAj/ttfwZnlXSglJUDfNmgizv/yeVlE3N1qyS1AFOtywXR+omFrMkL6yrpmYtQtSaXEW0pTMOGJOGxbU8oNCtEv7UrVcLo8X+OP1BLAQIUABQAAAAIAAAAIQAKCHnMDAEAAKgCAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAhQAFAAAAAgAAAAhAAZZx4KzAAAAKAEAAAsAAAAAAAAAAAAAAAAAPQEAAF9yZWxzLy5yZWxzUEsBAhQAFAAAAAgAAAAhAHdA/sS+AAAAHAEAAA8AAAAAAAAAAAAAAAAAGQIAAHhsL3dvcmtib29rLnhtbFBLAQIUABQAAAAIAAAAIQDgQpaKyQAAAKgBAAAaAAAAAAAAAAAAAAAAAAQDAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQIUABQAAAAIAAAAIQCNlKlJ6gAAAJcBAAANAAAAAAAAAAAAAAAAAAUEAAB4bC9zdHlsZXMueG1sUEsBAhQAFAAAAAgAAAAhAAea6KKEAAAAnQAAABgAAAAAAAAAAAAAAAAAGgUAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLBQYAAAAABgAGAIABAADUBQAAAAA=";
