/**
 * Internal ChainReact CLI — `app action scaffold <provider> <action>` command.
 *
 * Creates the SMALLEST repo-conventional action UNIT for an EXISTING provider: a
 * handler + schema + meta triad. It invents NOTHING — no scopes, no API endpoints,
 * no real behavior, no secrets, no network. The generated handler validates its
 * (already engine-resolved) config and then THROWS a clear "not implemented"
 * error, so a scaffolded action can never be mistaken for production-ready. The
 * meta is minimal but Zod-valid (no fields, no outputs, category "other") so the
 * provider keeps passing `app validate`.
 *
 * Layout: the dominant/new-provider convention is the SIBLING triad
 * (`actions/<base>.ts` + `.schema.ts` + `.meta.ts`); only hubspot uses an
 * `actions/meta/` subfolder for metas. We preserve a provider's existing
 * convention — if `actions/meta/` already exists, the meta goes there; otherwise
 * sibling.
 *
 * Writes go through the injectable `FsWriter`; reads/validation through `FsDeps`.
 * The predicted validation comes from an in-memory OVERLAY (plan + real repo) so
 * `--dry-run` shows the exact verdict a real run produces. Pure + testable.
 */
import { camelCaseId, registrationStatus } from "../registry";
import type { FsDeps, FsWriter } from "../repo";
import { collectActionUnits, listKnownProviders } from "../providers";
import { normalizeProviderId, overlayFs } from "./appScaffold";
import { renderValidation, validateProvider } from "./appValidate";

/** Action ids: lowercase words (letter-led) separated by single `-`/`_`. */
const ACTION_ID = /^[a-z][a-z0-9]*([-_][a-z0-9]+)*$/;

const cap = (w: string): string => w.charAt(0).toUpperCase() + w.slice(1);

export interface NormalizedAction {
  readonly ok: boolean;
  /** snake_case — used for the ActionMeta `type` + the `<provider>:<type>` key. */
  readonly type: string;
  /** camelCase — file basename + exported handler const. */
  readonly base: string;
  /** PascalCase — schema const prefix (`<Pascal>ConfigSchema`). */
  readonly pascal: string;
  /** Title Case — default displayName ("Send Test Message"). */
  readonly display: string;
  readonly error?: string;
}

/** Normalize + validate a raw action id into the repo's naming forms. Pure. */
export function normalizeActionId(raw: string): NormalizedAction {
  const id = (raw ?? "").trim().toLowerCase();
  const empty: Omit<NormalizedAction, "ok" | "error"> = { type: "", base: "", pascal: "", display: "" };
  if (!id) return { ok: false, ...empty, error: "Action id is required: `app action scaffold <provider> <action>`." };
  if (!ACTION_ID.test(id)) {
    return {
      ok: false,
      ...empty,
      error: `Invalid action id "${raw}". Use lowercase words separated by a single - or _ (e.g. send-test-message), starting with a letter.`,
    };
  }
  const words = id.split(/[-_]/);
  return {
    ok: true,
    type: words.join("_"),
    base: words.map((w, i) => (i === 0 ? w : cap(w))).join(""),
    pascal: words.map(cap).join(""),
    display: words.map(cap).join(" "),
  };
}

export interface ActionScaffoldFile {
  readonly path: string;
  readonly content: string;
}

/** The meta export-const name, e.g. `slackSendTestMessageMeta`. */
export function actionMetaExportName(provider: string, action: NormalizedAction): string {
  return `${camelCaseId(provider)}${action.pascal}Meta`;
}

/** Meta lives in `actions/meta/` only when the provider already uses that layout. */
export function chooseMetaPath(fs: FsDeps, provider: string, base: string): string {
  const metaDir = `integrations/${provider}/actions/meta`;
  return fs.isDirectory(metaDir) ? `${metaDir}/${base}.meta.ts` : `integrations/${provider}/actions/${base}.meta.ts`;
}

// ── generated file contents (syntactically valid TS; intentionally TODO) ─────

function handlerContent(provider: string, a: NormalizedAction): string {
  return `import type { ActionHandler } from "@/services/execution/handlers/types";
import { ${a.pascal}ConfigSchema } from "./${a.base}.schema";

/**
 * ${provider} \`${a.type}\` action handler — SCAFFOLD (not implemented).
 *
 * Generated by \`chainreact app action scaffold ${provider} ${a.type}\`. This is a
 * placeholder: it validates the resolved config for defense-in-depth and then
 * THROWS. It performs NO provider/network call and returns NO fake success — so it
 * can never be mistaken for production-ready.
 *
 * TODO(${provider}): implement the real ${a.type} behavior:
 *   - look up the account-owned integration + decrypt its token (see existing
 *     ${provider} handlers for the pattern),
 *   - call the provider API (add a typed client under integrations/${provider}/api/),
 *   - return a stable \`output\` object (becomes {{nodeId.<field>}} downstream),
 *   - register this handler in services/execution/handlers/_registry.ts and its
 *     meta in services/discovery/_registry.ts so the action loads in the app.
 */
export const ${a.base}: ActionHandler = async (input) => {
  // The engine already resolved every {{...}} reference; re-validate here.
  ${a.pascal}ConfigSchema.parse(input.config);
  throw new Error(
    "${provider}:${a.type} is not implemented yet (scaffolded placeholder — see the TODOs in this file).",
  );
};
`;
}

function schemaContent(provider: string, a: NormalizedAction): string {
  return `import { z } from "zod";

/**
 * Resolved-config schema for the ${provider} ${a.type} action — SCAFFOLD.
 *
 * Empty until you add real fields. Keep it in sync with \`${a.base}.meta.ts\`
 * \`fields[]\` — each meta field \`name\` should match a schema property.
 *
 * TODO(${provider}): add the action's config fields, e.g.
 *   z.object({ channel: z.string().min(1, "Channel is required.") })
 */
export const ${a.pascal}ConfigSchema = z.object({});
export type ${a.pascal}Config = z.infer<typeof ${a.pascal}ConfigSchema>;
`;
}

function metaContent(provider: string, a: NormalizedAction): string {
  const exportName = actionMetaExportName(provider, a);
  return `import type { ActionMeta } from "@/contracts/actionMeta";

/**
 * Builder-facing metadata for \`${provider}:${a.type}\` — SCAFFOLD.
 *
 * Minimal + contract-valid: no fields, no outputs, category "other". The action
 * will NOT appear in the builder/AI until its meta is registered in
 * services/discovery/_registry.ts AND its handler in
 * services/execution/handlers/_registry.ts.
 *
 * TODO(${provider}): real displayName + description, a proper category, fields[]
 *   (mirroring ${a.base}.schema.ts), outputs[], and risk flags
 *   (isDestructive / requiresConfirmation / riskLevel) if it mutates provider state.
 */
export const ${exportName}: ActionMeta = {
  key: "${provider}:${a.type}",
  provider: "${provider}",
  type: "${a.type}",
  displayName: "${a.display}",
  description:
    "TODO(${provider}): describe what the ${a.type} action does. Scaffolded placeholder — not implemented yet.",
  category: "other",
  requiresIntegration: true,
  fields: [],
  outputs: [],
  // Safe defaults (mirror the ActionMetaSchema defaults — explicit because the
  // inferred ActionMeta type requires them). Adjust when you implement the action.
  producesFileRef: false,
  consumesFileRef: false,
  displayOrder: null,
  isDestructive: false,
  requiresConfirmation: false,
  riskLevel: "low",
};
`;
}

export interface ActionScaffoldPlan {
  readonly provider: string;
  readonly action: NormalizedAction;
  readonly metaExportName: string;
  readonly files: readonly ActionScaffoldFile[];
}

/** Build the deterministic file plan for a provider + normalized action. Pure-ish (reads layout via fs). */
export function buildActionScaffoldPlan(fs: FsDeps, provider: string, a: NormalizedAction): ActionScaffoldPlan {
  const dir = `integrations/${provider}/actions`;
  return {
    provider,
    action: a,
    metaExportName: actionMetaExportName(provider, a),
    files: [
      { path: `${dir}/${a.base}.ts`, content: handlerContent(provider, a) },
      { path: `${dir}/${a.base}.schema.ts`, content: schemaContent(provider, a) },
      { path: chooseMetaPath(fs, provider, a.base), content: metaContent(provider, a) },
    ],
  };
}

export interface ActionScaffoldOptions {
  readonly dryRun: boolean;
}

export interface ActionScaffoldOutcome {
  readonly code: number;
  readonly output: string;
}

const NEXT_STEPS = (provider: string): string[] => [
  `npm run chainreact -- app validate ${provider}`,
  "npm run chainreact -- app validate --all",
];

const MANUAL_TODOS = (provider: string, a: NormalizedAction): string[] => [
  `Implement the handler in ${a.base}.ts (it currently throws "not implemented").`,
  `Add real config fields to ${a.base}.schema.ts and mirror them in ${a.base}.meta.ts fields[].`,
  `Set a real category, displayName, description, outputs[], and risk flags in ${a.base}.meta.ts.`,
  `Register the handler in services/execution/handlers/_registry.ts (key "${provider}:${a.type}").`,
  "Register the meta in services/discovery/_registry.ts so it appears in the builder + AI.",
  "Add tests (see tests/ conventions; discovery-meta-coverage for covered providers).",
];

/**
 * Orchestrate action scaffold. Reads + validation via `fs`; writes via `writer`
 * (skipped on dry-run). Returns an exit code + rendered output. Refuses unknown
 * providers, invalid action ids, and collisions with an existing action unit.
 */
export function runAppActionScaffold(
  rawProvider: string,
  rawAction: string,
  opts: ActionScaffoldOptions,
  fs: FsDeps,
  writer: FsWriter,
): ActionScaffoldOutcome {
  const np = normalizeProviderId(rawProvider);
  if (!np.ok) return { code: 2, output: `Error: ${np.error}` };
  const provider = np.id;

  // Provider must already exist (action scaffold never creates a provider).
  if (!fs.exists(`integrations/${provider}/manifest.ts`)) {
    const known = listKnownProviders(fs);
    return {
      code: 2,
      output: `Error: integrations/${provider}/manifest.ts does not exist — unknown provider. Create it first with \`chainreact app scaffold ${provider}\`. Known providers: ${known.join(", ") || "(none found)"}.`,
    };
  }

  const a = normalizeActionId(rawAction);
  if (!a.ok) return { code: 2, output: `Error: ${a.error}` };

  // Collision: refuse if an action unit with this basename already exists, or any
  // target file is already present (covers sibling + actions/meta/ layouts).
  const existingUnits = collectActionUnits(fs, `integrations/${provider}/actions`);
  const plan = buildActionScaffoldPlan(fs, provider, a);
  const present = plan.files.map((f) => f.path).filter((p) => fs.exists(p));
  if (existingUnits.has(a.base) || present.length > 0) {
    const what = present.length > 0 ? present.join(", ") : `an action named '${a.base}'`;
    return {
      code: 2,
      output: `Error: ${provider} already has ${what} — refusing to overwrite (no --force). Pick a different action id or edit the existing files.`,
    };
  }

  const predicted = validateProvider(provider, overlayFs(fs, plan.files));
  const unregistered = registrationStatus(fs, provider) === "unregistered";

  const lines: string[] = [];
  lines.push(`ChainReact — app action scaffold: ${provider}:${a.type}${opts.dryRun ? " (dry-run)" : ""}`);
  lines.push("");
  lines.push(`Files ${opts.dryRun ? "that would be created" : "created"} (${plan.files.length}):`);
  for (const f of plan.files) lines.push(`  ${opts.dryRun ? "would write" : "wrote"}: ${f.path}`);
  lines.push("");
  lines.push(`Action key: ${provider}:${a.type}   meta export: ${plan.metaExportName}`);
  lines.push("");

  if (unregistered) {
    lines.push(
      `WARNING: provider '${provider}' is not registered in integrations/_registry.ts — this action will NOT load in the app until the provider is wired (\`chainreact app register ${provider}\`). The files are still created.`,
      "",
    );
  }

  if (!opts.dryRun) {
    for (const f of plan.files) {
      const slash = f.path.lastIndexOf("/");
      if (slash > 0) writer.ensureDir(f.path.slice(0, slash));
      writer.writeFile(f.path, f.content);
    }
  }

  lines.push("Validation (predicted from the generated files):");
  lines.push(...renderValidation(predicted).split("\n").map((l) => `  ${l}`));
  lines.push("");

  lines.push("Manual TODOs (the scaffold invents nothing):");
  for (const t of MANUAL_TODOS(provider, a)) lines.push(`  - ${t}`);
  lines.push("");
  lines.push("Next commands:");
  for (const c of NEXT_STEPS(provider)) lines.push(`  ${c}`);
  lines.push("");
  lines.push(
    predicted.ok
      ? `The action triad PASSES \`app validate ${provider}\` now (complete, valid meta — no fields/outputs yet). The handler is a placeholder that THROWS until you implement it; it is NOT registered in the execution/discovery registries, so it does not run or appear in the builder yet. Once you implement the handler, wire it in with \`chainreact app action register ${provider} ${a.type}\` (it refuses while the handler is still a placeholder).`
      : `NOTE: the generated action does not pass validation — see the validation block above.`,
  );

  return { code: predicted.ok ? 0 : 1, output: lines.join("\n") };
}
