/**
 * Internal ChainReact CLI — `app scaffold <provider>` command.
 *
 * Creates the SMALLEST conventional provider skeleton: a single complete,
 * Zod-valid `integrations/<provider>/manifest.ts` with explicit TODO comments for
 * every human/provider-specific decision. It invents NOTHING — no scopes, no API
 * endpoints, no actions/triggers, no secrets, no network calls. Capabilities are
 * all `false` and scopes empty (an honest "nothing implemented yet" state that is
 * contract-valid), so the skeleton passes `app validate` immediately while making
 * the remaining work obvious.
 *
 * Why manifest-only: the repo registers manifests by EXPLICIT import in
 * `integrations/_registry.ts` (so a scaffolded manifest is inert until a developer
 * wires it), no provider ships a README/TODO file (so we don't add one — TODOs live
 * as manifest comments + printed guidance), and empty `actions/`/`triggers/` dirs
 * aren't git-tracked. Generating placeholder actions would be "inventing behavior".
 *
 * Writes go through the injectable `FsWriter`; reads/validation through `FsDeps`.
 * The validation result is computed from an in-memory OVERLAY (plan + real repo) so
 * `--dry-run` predicts the exact same verdict a real run produces. Pure + testable.
 */
import { renderValidation, validateProvider } from "./appValidate";
import type { FsDeps, FsWriter } from "../repo";

/** Provider ids: lowercase, start with a letter, `[a-z0-9_-]` (ProviderIdSchema). */
const PROVIDER_ID = /^[a-z][a-z0-9_-]*$/;

export interface NormalizedId {
  readonly ok: boolean;
  readonly id: string;
  readonly error?: string;
}

/** Normalize + validate a raw provider id (trim + lowercase, then contract regex). */
export function normalizeProviderId(raw: string): NormalizedId {
  const id = (raw ?? "").trim().toLowerCase();
  if (!id) return { ok: false, id, error: "Provider id is required: `app scaffold <provider>`." };
  if (!PROVIDER_ID.test(id)) {
    return {
      ok: false,
      id,
      error: `Invalid provider id "${raw}". Must match ${PROVIDER_ID} (lowercase, start with a letter, only a-z 0-9 - _).`,
    };
  }
  return { ok: true, id };
}

/** `google-analytics` → `googleAnalytics` (manifest export const naming). */
export function camelCaseId(id: string): string {
  return id
    .split(/[-_]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

/** `google-analytics` → `Google Analytics` (humanized displayName default). */
export function humanizeId(id: string): string {
  return id
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
}

export interface ScaffoldPlan {
  readonly providerId: string;
  readonly files: readonly ScaffoldFile[];
}

/** The generated manifest skeleton — contract-valid, capabilities off, TODO-marked. */
export function buildManifestContent(id: string): string {
  const exportName = `${camelCaseId(id)}Manifest`;
  const displayName = humanizeId(id);
  return `import {
  ProviderManifestSchema,
  type ProviderManifest,
} from "@/contracts/integration";

/**
 * ${displayName} provider manifest — SCAFFOLD.
 *
 * Generated by \`chainreact app scaffold ${id}\`. This is a minimal, contract-valid
 * skeleton: capabilities are all false and scopes empty, so nothing is exposed
 * until you implement it. Fill in the TODOs, then wire it up.
 *
 * TODO(${id}): register this manifest in integrations/_registry.ts (explicit import).
 * TODO(${id}): OAuth / client setup — implement integrations/${id}/oauth.ts (or auth.ts
 *              for token-ingest) and set capabilities.oauth + authFlow accordingly.
 * TODO(${id}): required scopes — add the provider's real scopes to scopes.required.
 * TODO(${id}): API endpoints / base URL — add to integrations/_shared/${id}/ helpers.
 * TODO(${id}): real actions — add integrations/${id}/actions/<name>.{ts,schema.ts,meta.ts}
 *              and register the handler in services/execution/handlers/_registry.ts.
 * TODO(${id}): real triggers — add integrations/${id}/triggers/<name>/ if the provider
 *              supports webhooks/polling; set capabilities.webhookTrigger/pollingTrigger.
 * TODO(${id}): field definitions — define action/trigger field metas (see contracts/actionMeta.ts).
 * TODO(${id}): tests — add provider tests (see tests/ conventions; discovery-meta-coverage).
 * TODO(${id}): app icon + category decisions, and flip isEnabled to true when ready.
 * TODO(${id}): tokenScope — confirm "user" vs "workspace" (workspace needs accountIdField).
 * TODO(${id}): healthCheckIntervalMs — pick the right tier (Google/MS 6h, Slack/etc 4h, others 12h).
 */
export const ${exportName}: ProviderManifest = ProviderManifestSchema.parse({
  id: "${id}",
  displayName: "${displayName}",
  // Skeleton is not connectable yet — flip to true once OAuth + actions are real.
  isEnabled: false,
  tokenScope: "user",
  oauthFlows: [],
  scopes: {
    required: [],
    optional: [],
    deprecated: [],
  },
  capabilities: {
    oauth: false,
    webhookTrigger: false,
    pollingTrigger: false,
    actions: false,
  },
  // 12h "other providers" tier — adjust to the provider's rate-limit profile.
  healthCheckIntervalMs: 12 * 60 * 60 * 1000,
  refreshable: false,
});
`;
}

/** Build the deterministic scaffold plan for a provider id. Pure. */
export function buildScaffoldPlan(id: string): ScaffoldPlan {
  return {
    providerId: id,
    files: [{ path: `integrations/${id}/manifest.ts`, content: buildManifestContent(id) }],
  };
}

/**
 * Read-overlay: a base `FsDeps` plus virtual files (the plan). Lets `--dry-run`
 * predict validation without writing, and a real run validate the just-written
 * files deterministically.
 */
export function overlayFs(base: FsDeps, files: readonly ScaffoldFile[]): FsDeps {
  const norm = (p: string): string => p.split("\\").join("/").replace(/\/+$/, "");
  const vFiles = new Map<string, string>();
  const vDirs = new Set<string>();
  for (const f of files) {
    const n = norm(f.path);
    vFiles.set(n, f.content);
    const parts = n.split("/");
    for (let i = 1; i < parts.length; i += 1) vDirs.add(parts.slice(0, i).join("/"));
  }
  return {
    exists: (p) => vFiles.has(norm(p)) || vDirs.has(norm(p)) || base.exists(p),
    isDirectory: (p) => vDirs.has(norm(p)) || base.isDirectory(p),
    listDir: (p) => {
      const n = norm(p);
      const out = new Set<string>(base.listDir(p));
      for (const f of vFiles.keys()) {
        if (f.startsWith(`${n}/`)) {
          const child = f.slice(n.length + 1).split("/")[0];
          if (child) out.add(child);
        }
      }
      return [...out];
    },
    readText: (p) => vFiles.get(norm(p)) ?? base.readText(p),
  };
}

export interface ScaffoldOptions {
  readonly dryRun: boolean;
}

export interface ScaffoldOutcome {
  readonly code: number;
  readonly output: string;
}

const NEXT_STEPS = (id: string): string[] => [
  `npm run chainreact -- app validate ${id}`,
  "npm run chainreact -- app validate --all",
  "npm run chainreact -- app list",
];

const MANUAL_TODOS = (id: string): string[] => [
  `Register the manifest in integrations/_registry.ts (explicit import of ${camelCaseId(id)}Manifest).`,
  "Implement OAuth/client setup (oauth.ts or auth.ts) and set capabilities.oauth + authFlow.",
  "Add the provider's real required scopes.",
  "Add real actions (handler + schema + meta) and register the handlers.",
  "Add real triggers if the provider supports webhooks/polling.",
  "Decide app icon + category; flip isEnabled to true when the provider is ready.",
];

/**
 * Orchestrate scaffold. Reads + validation via `fs`; writes via `writer` (skipped
 * on dry-run). Returns an exit code + rendered output. Never overwrites: refuses
 * if the provider directory already exists.
 */
export function runAppScaffold(rawId: string, opts: ScaffoldOptions, fs: FsDeps, writer: FsWriter): ScaffoldOutcome {
  const norm = normalizeProviderId(rawId);
  if (!norm.ok) return { code: 2, output: `Error: ${norm.error}` };
  const id = norm.id;

  const dir = `integrations/${id}`;
  if (fs.isDirectory(dir)) {
    return {
      code: 2,
      output: `Error: integrations/${id}/ already exists — refusing to overwrite (no --force in this command). Pick a new id or remove the existing provider yourself.`,
    };
  }

  const plan = buildScaffoldPlan(id);
  // Predict the validation verdict from an overlay (plan + real repo) — identical
  // for dry-run and a real write.
  const predicted = validateProvider(id, overlayFs(fs, plan.files));

  const lines: string[] = [];
  lines.push(`ChainReact — app scaffold: ${id}${opts.dryRun ? " (dry-run)" : ""}`);
  lines.push("");
  lines.push(`Files ${opts.dryRun ? "that would be created" : "created"} (${plan.files.length}):`);
  for (const f of plan.files) lines.push(`  ${opts.dryRun ? "would write" : "wrote"}: ${f.path}`);
  lines.push("");

  if (!opts.dryRun) {
    writer.ensureDir(dir);
    for (const f of plan.files) writer.writeFile(f.path, f.content);
  }

  // Validation result (predicted from the plan).
  lines.push("Validation (predicted from the generated files):");
  lines.push(...renderValidation(predicted).split("\n").map((l) => `  ${l}`));
  lines.push("");

  lines.push("Manual TODOs (the scaffold invents nothing):");
  for (const t of MANUAL_TODOS(id)) lines.push(`  - ${t}`);
  lines.push("");
  lines.push("Next commands:");
  for (const c of NEXT_STEPS(id)) lines.push(`  ${c}`);
  lines.push("");
  lines.push(
    predicted.ok
      ? `The skeleton PASSES \`app validate ${id}\` now (complete manifest, no actions/triggers yet). It is NOT yet wired into the app — see the Manual TODOs. It will not appear in the running app until registered in integrations/_registry.ts.`
      : `NOTE: the generated skeleton does not pass validation — see the validation block above.`,
  );

  // Dry-run is a planning success when the plan validates; a real run's code
  // follows the validation verdict.
  const code = predicted.ok ? 0 : 1;
  return { code, output: lines.join("\n") };
}
