/**
 * Internal ChainReact CLI — `app trigger scaffold <provider> <trigger>` command.
 *
 * Creates the SMALLEST repo-conventional trigger unit for an EXISTING provider: a
 * single meta file in the dominant folder-per-trigger layout
 * `integrations/<provider>/triggers/<base>/<base>.meta.ts`. Triggers do NOT follow
 * the action handler/schema/meta triad — runtime arming (webhook subscription /
 * polling / filter) lives in activation-specific files (`activate.ts`, `poll.ts`,
 * `filter.ts`, …) that encode REAL provider behavior, so the scaffold invents NONE
 * of them. It emits ONLY the builder/AI metadata, with `activation: "manual"` (an
 * inert shape: fired only by run-now — no subscription, no poll), so the
 * scaffolded trigger is never accidentally runnable/subscribable.
 *
 * The meta is minimal but Zod-valid (no fields, empty payloadShape, category
 * "other") so the provider keeps passing `app validate`. The trigger is NOT
 * registered in the discovery inventory — registration is a documented manual
 * step (no `app trigger register` this slice; see README).
 *
 * Writes go through the injectable `FsWriter`; reads/validation through `FsDeps`.
 * Predicted validation comes from an OVERLAY (plan + real repo). Pure + testable.
 */
import { camelCaseId, registrationStatus } from "../registry";
import { collectActionUnits, listKnownProviders } from "../providers";
import type { FsDeps, FsWriter } from "../repo";
import { normalizeActionId, type NormalizedAction } from "./appActionScaffold";
import { normalizeProviderId, overlayFs } from "./appScaffold";
import { renderValidation, validateProvider } from "./appValidate";

/** Trigger meta export-const name, e.g. `slackMessagePostedTriggerMeta`. */
export function triggerMetaExportName(provider: string, t: NormalizedAction): string {
  return `${camelCaseId(provider)}${t.pascal}TriggerMeta`;
}

/** Folder-per-trigger layout: `integrations/<provider>/triggers/<base>/<base>.meta.ts`. */
export function triggerMetaPath(provider: string, base: string): string {
  return `integrations/${provider}/triggers/${base}/${base}.meta.ts`;
}

/** Generate the inert, Zod-valid TriggerMeta skeleton (manual activation, TODO). */
export function buildTriggerMetaContent(provider: string, t: NormalizedAction): string {
  const exportName = triggerMetaExportName(provider, t);
  return `import type { TriggerMeta } from "@/contracts/triggerMeta";

/**
 * Builder-facing metadata for \`${provider}:${t.type}\` — SCAFFOLD.
 *
 * Generated by \`chainreact app trigger scaffold ${provider} ${t.type}\`. Minimal +
 * contract-valid: no fields, empty payloadShape, category "other", and
 * \`activation: "manual"\` — an INERT shape (fired only by run-now; no webhook
 * subscription, no polling) so the scaffold invents no real trigger behavior.
 *
 * It is NOT wired into the discovery inventory, so it won't appear in the
 * builder/AI until registered (manual step — there is no auto-registration).
 *
 * TODO(${provider}): real displayName + description, a proper category, the real
 *   \`activation\` (webhook | polling | scheduled) + its runtime files
 *   (activate/deactivate/poll/filter/index — encode the provider's actual
 *   subscription/poll behavior), fields[] the user configures, and payloadShape[]
 *   the trigger emits to downstream nodes. Then register the meta in
 *   services/discovery/_metaInventory.ts (ALL_TRIGGER_META) or the provider's
 *   discovery barrel (<X>_TRIGGER_METAS).
 */
export const ${exportName}: TriggerMeta = {
  key: "${provider}:${t.type}",
  provider: "${provider}",
  type: "${t.type}",
  displayName: "${t.display}",
  description:
    "TODO(${provider}): describe when the ${t.type} trigger fires. Scaffolded placeholder — not implemented yet.",
  category: "other",
  // Inert until implemented — change to webhook/polling/scheduled with real
  // runtime files. Confirm requiresIntegration matches the real activation.
  activation: "manual",
  requiresIntegration: true,
  fields: [],
  payloadShape: [],
  displayOrder: null,
};
`;
}

export interface TriggerScaffoldFile {
  readonly path: string;
  readonly content: string;
}

export interface TriggerScaffoldPlan {
  readonly provider: string;
  readonly trigger: NormalizedAction;
  readonly metaExportName: string;
  readonly files: readonly TriggerScaffoldFile[];
}

/** Build the deterministic file plan (one meta file). Pure. */
export function buildTriggerScaffoldPlan(provider: string, t: NormalizedAction): TriggerScaffoldPlan {
  return {
    provider,
    trigger: t,
    metaExportName: triggerMetaExportName(provider, t),
    files: [{ path: triggerMetaPath(provider, t.base), content: buildTriggerMetaContent(provider, t) }],
  };
}

export interface TriggerScaffoldOptions {
  readonly dryRun: boolean;
}

export interface TriggerScaffoldOutcome {
  readonly code: number;
  readonly output: string;
}

const NEXT_STEPS = (provider: string): string[] => [
  `npm run chainreact -- app validate ${provider}`,
  "npm run chainreact -- app validate --all",
];

const MANUAL_TODOS = (provider: string, t: NormalizedAction): string[] => [
  `Decide the real activation (webhook | polling | scheduled) and add its runtime files under triggers/${t.base}/ (activate/deactivate/poll/filter/index — encode the provider's actual behavior).`,
  `Set a real category, displayName, description, fields[], and payloadShape[] in ${t.base}.meta.ts.`,
  `Register the meta in services/discovery/_metaInventory.ts (ALL_TRIGGER_META) or the provider's discovery barrel (<X>_TRIGGER_METAS) — there is no auto-registration for triggers.`,
  "Add tests (see tests/ conventions; discovery-meta-coverage for covered providers).",
];

/**
 * Orchestrate trigger scaffold. Reads + validation via `fs`; writes via `writer`
 * (skipped on dry-run). Refuses unknown providers, invalid trigger ids, and
 * collisions with an existing trigger unit/folder.
 */
export function runAppTriggerScaffold(
  rawProvider: string,
  rawTrigger: string,
  opts: TriggerScaffoldOptions,
  fs: FsDeps,
  writer: FsWriter,
): TriggerScaffoldOutcome {
  const np = normalizeProviderId(rawProvider);
  if (!np.ok) return { code: 2, output: `Error: ${np.error}` };
  const provider = np.id;

  if (!fs.exists(`integrations/${provider}/manifest.ts`)) {
    const known = listKnownProviders(fs);
    return {
      code: 2,
      output: `Error: integrations/${provider}/manifest.ts does not exist — unknown provider. Create it first with \`chainreact app scaffold ${provider}\`. Known providers: ${known.join(", ") || "(none found)"}.`,
    };
  }

  const t = normalizeActionId(rawTrigger);
  if (!t.ok) return { code: 2, output: `Error: ${t.error}` };

  // Collision: refuse if a trigger unit with this basename exists, the target meta
  // file exists, or the trigger folder already exists.
  const existing = collectActionUnits(fs, `integrations/${provider}/triggers`);
  const plan = buildTriggerScaffoldPlan(provider, t);
  const metaFile = plan.files[0]!.path;
  const folder = `integrations/${provider}/triggers/${t.base}`;
  if (existing.has(t.base) || fs.exists(metaFile) || fs.isDirectory(folder)) {
    return {
      code: 2,
      output: `Error: ${provider} already has a trigger '${t.base}' (or ${folder}/ exists) — refusing to overwrite (no --force). Pick a different trigger id or edit the existing files.`,
    };
  }

  const predicted = validateProvider(provider, overlayFs(fs, plan.files));
  const unregistered = registrationStatus(fs, provider) === "unregistered";

  const lines: string[] = [];
  lines.push(`ChainReact — app trigger scaffold: ${provider}:${t.type}${opts.dryRun ? " (dry-run)" : ""}`);
  lines.push("");
  lines.push(`Files ${opts.dryRun ? "that would be created" : "created"} (${plan.files.length}):`);
  for (const f of plan.files) lines.push(`  ${opts.dryRun ? "would write" : "wrote"}: ${f.path}`);
  lines.push("");
  lines.push(`Trigger key: ${provider}:${t.type}   meta export: ${plan.metaExportName}   activation: manual (inert)`);
  lines.push("");

  if (unregistered) {
    lines.push(
      `WARNING: provider '${provider}' is not registered in integrations/_registry.ts — this trigger will NOT load in the app until the provider is wired (\`chainreact app register ${provider}\`). The file is still created.`,
      "",
    );
  }

  if (!opts.dryRun) {
    writer.ensureDir(folder);
    for (const f of plan.files) writer.writeFile(f.path, f.content);
  }

  lines.push("Validation (predicted from the generated files):");
  lines.push(...renderValidation(predicted).split("\n").map((l) => `  ${l}`));
  lines.push("");
  lines.push("Manual TODOs (the scaffold invents nothing):");
  for (const todo of MANUAL_TODOS(provider, t)) lines.push(`  - ${todo}`);
  lines.push("");
  lines.push("Next commands:");
  for (const c of NEXT_STEPS(provider)) lines.push(`  ${c}`);
  lines.push("");
  lines.push(
    predicted.ok
      ? `The trigger meta PASSES \`app validate ${provider}\` now (complete, valid meta — manual activation, no fields/payload yet). It is INERT (no webhook/polling runtime) and NOT registered in the discovery inventory, so it does not run or appear in the builder yet. \`app validate\` will warn TRIGGER_META_NOT_REGISTERED until you register it (manual step — see README).`
      : `NOTE: the generated trigger does not pass validation — see the validation block above.`,
  );

  return { code: predicted.ok ? 0 : 1, output: lines.join("\n") };
}
