import {
  ProviderManifestSchema,
  type ProviderManifest,
} from "@/contracts/integration";

/**
 * Motive (gomotive.com, formerly KeepTruckin) provider manifest — MOTIVE-1.
 *
 * Fleet-management / telematics platform. Wire-format verified against Motive's
 * official developer docs (docs/providers/motive/research.md, 2026-07-17).
 *
 * Auth model — OAuth 2.0 authorization code, confidential client, NO PKCE,
 * body-auth token exchange, refreshable:
 *   - `authorize`: `https://account.gomotive.com/oauth/authorize`
 *   - `token`:     `https://account.gomotive.com/oauth/token`
 *     (LIVE-CORRECTED 2026-07-24: the docs' bare `gomotive.com` host only
 *     works for authorize because the browser follows a redirect to
 *     `account.gomotive.com`; a server-side token POST to it returns 404)
 *   - Access tokens expire after 2 hours (`expires_in: 7200`); refresh tokens
 *     are SINGLE-USE / rotating — `oauth.ts` persists the returned refresh token
 *     on every exchange/refresh (Calendly/QuickBooks rotation-persist shape).
 *
 * Company scoping — a Motive grant authorizes ONE company's data. The company
 * id is read from `GET /v1/users/me` at connect time and stored as the
 * `providerAccountId`. `accountIdField: "companyId"` — it is both the
 * multi-company discriminator (one authorization = one company; two companies =
 * two integration rows) and the webhook fan-out scope.
 *
 * tokenScope: "user" — keyed per connecting user; multi-company discrimination
 * rides on providerAccountId (companyId). The credential CLASS is `account`
 * (core/integrations/credentialSharing.ts): a Motive connection represents the
 * company's fleet — a shared business resource the operations team jointly
 * manages — NOT one person's private data (Stripe/QuickBooks posture).
 *
 * apiVersion: "v1" — fuel/vehicles/users/webhooks are all `/v1/`.
 *
 * Health-check interval: 12h ("Others" bucket). 2-hour access tokens between
 * checks are handled reactively by `refreshAndRetry`.
 *
 * Capabilities (honest — nothing "coming soon"):
 *   - `oauth: true` — code flow + rotating refresh implemented.
 *   - `actions: true` — 10 bounded action handlers ship (fuel CRUD + bulk CSV
 *     import + send message + create/update vehicle + update driver).
 *   - `webhookTrigger: true` — 7 per-company webhook triggers
 *     (`POST /v1/company_webhooks`; secret generated by V2, HMAC-SHA1 verified).
 *   - `pollingTrigger: true` — `new_fuel_purchase` (Motive exposes no
 *     fuel-purchase webhook); baseline-first.
 */
export const motiveManifest: ProviderManifest = ProviderManifestSchema.parse({
  id: "motive",
  displayName: "Motive",
  isEnabled: true,
  apiVersion: "v1",
  tokenScope: "user",
  oauthFlows: ["v2"],
  accountIdField: "companyId",
  // Exact Doorkeeper scope identifiers (11) — one per developer-portal
  // permission row. LIVE-VERIFIED 2026-07-24 (single-scope authorize bisect
  // against the real app): each portal row grants EXACTLY ONE variant chosen by
  // its Read-only / Read-and-write dropdown — "Read and write" REPLACES `.read`
  // with `.manage` (requesting both 403s the whole authorize request with
  // "requested scope is invalid"). So `.read` is requested ONLY for rows the
  // portal keeps at Read only. Motive labels `.manage` as "Read and write" —
  // GET endpoints under a manage-only row (fuel list/get, driver/vehicle
  // pickers, fuel-purchase polling) ride the manage scope; verify at Phase 13.
  // `company_webhooks.manage` is MANDATORY for the 7 webhook triggers
  // (POST /v1/company_webhooks) — live-verified valid despite being absent from
  // Motive's public scope docs. Deliberately NOT requested: `forms.read` /
  // `form_entries.read` are DISPATCH-FORMS permissions and do NOT authorize
  // Inspection Reports — `inspection_reports.read` does (portal row stays
  // Read only).
  scopes: {
    required: [
      "companies.read",
      "fuel_purchases.manage",
      "vehicles.manage",
      "users.manage",
      "messages.manage",
      "company_webhooks.manage",
      "inspection_reports.read",
      "hos_logs.hos_violation",
      "driver_performance_events.read",
      "speeding_events.read",
      "fault_codes.read",
    ],
    optional: [],
    deprecated: [],
  },
  capabilities: {
    oauth: true,
    webhookTrigger: true,
    pollingTrigger: true,
    actions: true,
  },
  healthCheckIntervalMs: 12 * 60 * 60 * 1000,
  refreshable: true,
});
