// This file is auto-generated by scripts/download-logos.mjs
export interface LogoConfig {
  name: string;
  path: string;
  category: string;
}

export const LOGO_CONFIG: Record<string, LogoConfig> = {
  'gmail': {
    name: 'Gmail',
    path: '/integrations/gmail.svg',
    category: 'Communication',
  },
  'google-calendar': {
    name: 'Google Calendar',
    path: '/integrations/google-calendar.svg',
    category: 'Productivity',
  },
  'google-drive': {
    name: 'Google Drive',
    path: '/integrations/google-drive.svg',
    category: 'Storage',
  },
  'google-sheets': {
    name: 'Google Sheets',
    path: '/integrations/google-sheets.svg',
    category: 'Productivity',
  },
  'youtube': {
    name: 'YouTube',
    path: '/integrations/youtube.svg',
    category: 'Social',
  },
  'microsoft-teams': {
    name: 'Microsoft Teams',
    path: '/integrations/microsoft-teams.svg',
    category: 'Communication',
  },
  'onedrive': {
    name: 'OneDrive',
    path: '/integrations/onedrive.svg',
    category: 'Storage',
  },
  'slack': {
    name: 'Slack',
    path: '/integrations/slack.svg',
    category: 'Communication',
  },
  'discord': {
    name: 'Discord',
    path: '/integrations/discord.svg',
    category: 'Communication',
  },
};
