-- ChainReactV2 — ledger anonymization + retention (Slice 4.ACCOUNT-MODEL-10d).
--
-- Changes the three account-owned ledgers so that, at account purge time, their
-- rows can be ANONYMIZED and RETAINED as non-account-addressable
-- audit/statistical records, then HARD-DELETED after a retention window — the
-- plan's anonymize → retain → delete policy, replacing 10c's
-- "deleted-with-account via account_id ON DELETE CASCADE" placeholder.
--
-- For each ledger:
--   1. account_id FK: ON DELETE CASCADE → ON DELETE SET NULL, column made
--      NULLABLE. (After anonymization account_id is NULL, so the row no longer
--      belongs to any account and is invisible to every account-membership RLS
--      policy — the EXISTS join never matches NULL.)
--   2. ai_cost_events.user_id FK: ON DELETE CASCADE → ON DELETE SET NULL,
--      NULLABLE (the actor reference is nulled during anonymization).
--   3. task_usage_events.workflow_run_id FK: ON DELETE CASCADE → ON DELETE
--      SET NULL (was the one remaining CASCADE that could delete a retained
--      ledger row when its run is deleted).
--   4. billing_shadow_comparisons.workflow_id / workflow_run_id (no FK,
--      correlation keys): made NULLABLE so anonymization can null them.
--   5. Add anonymized_at + ledger_purge_after to all three, plus a partial
--      index for the retention-cron worklist.
--
-- FK drops are catalog-introspected (drop whatever FK exists on the column) so
-- this migration does not depend on autogenerated constraint names. Idempotent.
--
-- NO new table → migration-RLS lint N/A. The account-membership SELECT policies
-- (re-pointed in 20260531000006) already gate on account_id; a NULL account_id
-- never matches, so anonymized rows are automatically non-addressable. No RLS
-- change needed.
--
-- ROLLBACK (pre-launch): re-add the columns' NOT NULL (after backfilling), drop
-- the anonymization columns + index, and restore the CASCADE FKs.

-- ── Helper: drop any FK on (table, column), then add a named SET NULL FK ──────

DO $$
DECLARE
  r record;
BEGIN
  -- Drop every existing FK constraint on the target columns across the three
  -- ledgers (whatever they are named).
  FOR r IN
    SELECT con.conname, rel.relname
      FROM pg_constraint con
      JOIN pg_class rel ON rel.oid = con.conrelid
      JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
      JOIN unnest(con.conkey) AS colnum ON true
      JOIN pg_attribute att
        ON att.attrelid = con.conrelid AND att.attnum = colnum
     WHERE con.contype = 'f'
       AND nsp.nspname = 'public'
       AND (
         (rel.relname = 'task_usage_events'         AND att.attname IN ('account_id','workflow_run_id')) OR
         (rel.relname = 'ai_cost_events'            AND att.attname IN ('account_id','user_id')) OR
         (rel.relname = 'billing_shadow_comparisons' AND att.attname IN ('account_id'))
       )
  LOOP
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', r.relname, r.conname);
  END LOOP;
END $$;

-- ── task_usage_events ────────────────────────────────────────────────────────

ALTER TABLE public.task_usage_events ALTER COLUMN account_id DROP NOT NULL;

ALTER TABLE public.task_usage_events
  ADD CONSTRAINT task_usage_events_account_id_fkey
  FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;

ALTER TABLE public.task_usage_events
  ADD CONSTRAINT task_usage_events_workflow_run_id_fkey
  FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_runs(id) ON DELETE SET NULL;

ALTER TABLE public.task_usage_events
  ADD COLUMN IF NOT EXISTS anonymized_at timestamptz,
  ADD COLUMN IF NOT EXISTS ledger_purge_after timestamptz;

CREATE INDEX IF NOT EXISTS task_usage_events_ledger_purge_idx
  ON public.task_usage_events (ledger_purge_after)
  WHERE anonymized_at IS NOT NULL;

-- ── ai_cost_events ───────────────────────────────────────────────────────────

ALTER TABLE public.ai_cost_events ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE public.ai_cost_events ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.ai_cost_events
  ADD CONSTRAINT ai_cost_events_account_id_fkey
  FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;

ALTER TABLE public.ai_cost_events
  ADD CONSTRAINT ai_cost_events_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.ai_cost_events
  ADD COLUMN IF NOT EXISTS anonymized_at timestamptz,
  ADD COLUMN IF NOT EXISTS ledger_purge_after timestamptz;

CREATE INDEX IF NOT EXISTS ai_cost_events_ledger_purge_idx
  ON public.ai_cost_events (ledger_purge_after)
  WHERE anonymized_at IS NOT NULL;

-- ── billing_shadow_comparisons ───────────────────────────────────────────────

ALTER TABLE public.billing_shadow_comparisons ALTER COLUMN account_id DROP NOT NULL;
-- workflow_id / workflow_run_id are correlation keys with NO FK — just relax NOT NULL.
ALTER TABLE public.billing_shadow_comparisons ALTER COLUMN workflow_id DROP NOT NULL;
ALTER TABLE public.billing_shadow_comparisons ALTER COLUMN workflow_run_id DROP NOT NULL;

ALTER TABLE public.billing_shadow_comparisons
  ADD CONSTRAINT billing_shadow_comparisons_account_id_fkey
  FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;

ALTER TABLE public.billing_shadow_comparisons
  ADD COLUMN IF NOT EXISTS anonymized_at timestamptz,
  ADD COLUMN IF NOT EXISTS ledger_purge_after timestamptz;

CREATE INDEX IF NOT EXISTS billing_shadow_comparisons_ledger_purge_idx
  ON public.billing_shadow_comparisons (ledger_purge_after)
  WHERE anonymized_at IS NOT NULL;
